language: php
php:
    - "5.6"
    - "7.0"
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - bundle exec rackup &
    - sleep 5
    - composer install --prefer-dist --no-interaction
    - cd public/ && curl -k https://bowerphp.org/bowerphp.phar > bowerphp.phar && php bower.phar install
    - cd ../
    - cp .env.example .env
    - php artisan key:generate
    - php artisan serve
script:
    - phantomjs public/js/appTest.js "http://localhost:8000/"
